#! /bin/sh
feh --bg-scale $HOME/media/wallpapers/wallpaper.jpg &
sxhkd &
numlockx on &
$HOME/.config/polybar/launch.sh &
$HOME/apps/clipmenu/clipmenud &
st &
compton -f -b &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Vlc desktop='^4'
bspc rule -a ReText desktop='^9' follow=on
bspc rule -a MuPDF desktop='^5'
bspc rule -a Chromium desktop='^2'follow=on
bspc rule -a Eclipse desktop='^3' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Atom desktop='^9' follow=on
bspc rule -a Dia desktop='^9' follow=on
bspc rule -a Google-chrome desktop='^2' follow=on
bspc rule -a libreoffice-writer desktop='^3' follow=on
